### ISSUE TITLE
How can I send a yaml-spec to Kubernetes without saving it before in a file

### ISSUE THREAD

**Issue by janbaer** [janbaer/howcani-data#252]
You can this this with the so called **EOF** pattern, as you can see in the following example

```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  password: $(echo -n "s33msi4" | base64 -w0)
  username: $(echo -n "jane" | base64 -w0)
EOF
```
