### ISSUE TITLE
How can I reuse items from one list into another list vars, without just copying the entries

### ISSUE THREAD

**Issue by janbaer** [janbaer/howcani-data#290]
The challenge is, to reuse items from the vars file of the **all** group, in the vars file of any other group.
The solution is, to define a list-variable called `global_any_list` and then use this list in both groups. In the **all** group vars it could look like 

```yaml
global_cron_jobs:
	- name: job1
    - name: job2
    
cron_jobs: "{{ global_cron_jobs }}"
```

In the vars file of the other group, you could do the following

```yaml
cron_jobs:
	- "{{ global_cron_jobs }}"
    - job3
    - job4
```
